[tool.poetry]
name = "python-devcontainer"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10.12"
numpy = "^2.1.3"
pandas = "^2.2.3"
jupyter = "^1.1.1"
ipywidgets = "^8.1.5"
jupyter-contrib-nbextensions = "^0.7.0"
nbconvert = "^7.16.4"



